### PR TITLE
Prep for open sourcing

### PR DESCRIPTION
**Pull request by mvd-ows**
add license, readme, bug fix.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/libwfp/14)

### CODE REVIEW

**Comment by mvd-ows** [comment]
I will merge the PR that deals with the Google Test submodule, and rebase. That should make Travis happy. But grateful if you could take a look at this in the meantime :-)

**Comment by mvd-ows** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[README.md, line 43 at r1](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-L9jn1WFCG98vmCArE1V:-L9jn1WFCG98vmCArE1W:b-tgh9ep) ([raw file](https://github.com/mullvad/libwfp/blob/28bf2dd2cfdd197233b3f26d3b644298cdde39c8/README.md#L43)):*
> ```Markdown
> int main()
> {
> 	auto engine = wfp::FilterEngine::DynamicSession();
> ```

Tabs... WTH. Will fix.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/libwfp/14)*

**Comment by mvd-ows** [comment]
*[src/libcommon/libcommon.vcxproj, line 133 at r1](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-L9jn8cD5Er3eRuvhOFE:-L9jn8cD5Er3eRuvhOFF:b-dsr4oi) ([raw file](https://github.com/mullvad/libwfp/blob/8e24c98fb627c9c32534e47cfa4deba7ffee1b91/src/libcommon/libcommon.vcxproj#L133)):*
> ```XML
>     </Link>
>     <Lib>
>       <AdditionalDependencies>advapi32.lib</AdditionalDependencies>
> ```

This must be a remnant from some old testing. Perfectly safe to remove.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/libwfp/14)*

**Comment by faern** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[LICENSE.md, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-L9jwyRtB5sotMWKLxZ4:-L9jwyRtB5sotMWKLxZ5:b-5nqv0m) ([raw file](https://github.com/mullvad/libwfp/blob/28bf2dd2cfdd197233b3f26d3b644298cdde39c8/LICENSE.md#L1)):*
> ```Markdown
> The MIT License (MIT)
> ```

I thought we said on slack to use GPL-3?
If not going with that license we might want to check with other people, such as Fredrik or Daniel, since they have been approving of licenses before. Opening a C++ library is untested territory for us, but going with GPL-3 probably don't require us to ask anyone since that is our preferred default license.

---

*[README.md, line 43 at r1](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-L9jn1WFCG98vmCArE1V:-L9jxRtABS10IGWpRn7M:b-dhizhs) ([raw file](https://github.com/mullvad/libwfp/blob/28bf2dd2cfdd197233b3f26d3b644298cdde39c8/README.md#L43)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Tabs... WTH. Will fix.
</blockquote></details>

Isn't the entire code base in tabs? At least the Mullvad specific stuff you submitted to `mullvadvpn-app` was. I also prefer spaces everywhere, it's what we use in all other projects we have in all other languages :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/libwfp/14)*

**Comment by faern** [comment]
I didn't review the C++ itself. Not sure if you intended me to do that. But good README.

---

Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-:-L9jySCQBPJ08JDvia8B:b-33n3m5)*

**Comment by mvd-ows** [comment]
Thanks, included you for license + readme discussions.

---

Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[LICENSE.md, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-L9jwyRtB5sotMWKLxZ4:-L9l1-03A-FswRHDBhQh:bj9vp05) ([raw file](https://github.com/mullvad/libwfp/blob/28bf2dd2cfdd197233b3f26d3b644298cdde39c8/LICENSE.md#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I thought we said on slack to use GPL-3?
If not going with that license we might want to check with other people, such as Fredrik or Daniel, since they have been approving of licenses before. Opening a C++ library is untested territory for us, but going with GPL-3 probably don't require us to ask anyone since that is our preferred default license.
</blockquote></details>

After giving it some thought it seemed that GPL might be too restrictive for a tiny library such as this one. It's one thing to release a large application; it wouldn't feel right if someone replaced the logo and started selling it as their own software. But for this library, I'd like to see it spread as far and wide as possible, and I don't see how restricting the usage will support this.

I will consult with Fredrik.

---

*[README.md, line 43 at r1](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-L9jn1WFCG98vmCArE1V:-L9l2XGP51fGRBB4uA_9:b7ytyqw) ([raw file](https://github.com/mullvad/libwfp/blob/28bf2dd2cfdd197233b3f26d3b644298cdde39c8/README.md#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Isn't the entire code base in tabs? At least the Mullvad specific stuff you submitted to `mullvadvpn-app` was. I also prefer spaces everywhere, it's what we use in all other projects we have in all other languages :)
</blockquote></details>

Yep, the C++ code uses tabs. But it looks stupid in the readme when it's rendered with a tab width of 8 characters.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-:-L9l3Q4-1lImDuXGDd5l:b-d1b48p)*

**Comment by faern** [comment]
Reviewed 1 of 7 files at r1, 1 of 1 files at r2.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[LICENSE.md, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-L9jwyRtB5sotMWKLxZ4:-L9nUZf7-NIDv9zzXLUu:bl5pu0q) ([raw file](https://github.com/mullvad/libwfp/blob/eb5b3beab641c2e77cd5a6e518df6f4cf6118547/LICENSE.md#L1)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

After giving it some thought it seemed that GPL might be too restrictive for a tiny library such as this one. It's one thing to release a large application; it wouldn't feel right if someone replaced the logo and started selling it as their own software. But for this library, I'd like to see it spread as far and wide as possible, and I don't see how restricting the usage will support this.

I will consult with Fredrik.
</blockquote></details>

Yes, ok. I'll approve this for now and we can revisit it if someone else don't agree :+1:

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/libwfp/14)*

**Comment by pinkisemils** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/libwfp/14#-:-L9nfZjt6ly6zSTPd-Mh:bnfp4nl)*

**Pull request merged**
